FROM python:3.8.3-slim-buster

LABEL maintainer="Soramon" version="0.1"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /home/sora/app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3-dev \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
COPY requirements ./requirements
RUN pip install -r requirements/dev.txt

COPY ./app .

EXPOSE 8000