version: "3.1"

services:
  db:
    container_name: noones_db
    image: postgres:12.3-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: sora_password
      POSTGRES_USER: sora
      POSTGRES_DB: dev_db
    volumes:
      - app_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: noones_redis
    image: redis:6.0.6
    networks:
      - backend
    volumes:
      - app_redis:/data
    ports:
      - "6379:6379"

networks:
  backend:

volumes:
  app_db:
  app_redis:
