version: "3.1"

services:
  web:
    networks:
      - backend
    volumes:
      - app_media:/home/sora/app/media
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    volumes:
      - app_db:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  app_media:
  app_db:
