version: "3.8"

services:
  web:
    image: soramon0/noc
    command: >
      sh -c python manage.py wait_for_db &&
            python manage.py migrate &&
            gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    secrets:
      - source: EMAIL_USER
      - source: EMAIL_PASS
      - source: POSTGRES_PASSWORD
      - source: POSTGRES_USER
    env_file:
      - ./.env.prod
  db:
    secrets:
      - source: POSTGRES_PASSWORD
      - source: POSTGRES_USER
    environment:
      POSTGRES_DB: noones

secrets:
  EMAIL_USER:
    external: true
  EMAIL_PASS:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_USER:
    external: true
