version: "3.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: noones_web
    volumes:
      - ./app:/home/sora/app
    ports:
      - "8000:8000"
      - "9001:9001"
    environment:
      POSTGRES_USER: sora
      POSTGRES_PASSWORD: sora_password
      POSTGRES_HOST: db
      POSTGRES_NAME: dev_db
      SECRET_KEY: super_secret_key
      DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "*"
    secrets:
      - source: email_user
      - source: email_pass
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py runserver 0.0.0.0:8000"

  client:
    image: node:14.3
    container_name: noones_client
    working_dir: /opt/node_app/static_src
    ports:
      # port for live reloading
      - "35729:35729"
    volumes:
      - ./app/theme/static:/opt/node_app/static
      - ./app/theme/static_src:/opt/node_app/static_src
      - ./app/theme/templates:/opt/node_app/templates
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_app/node_modules location.
      #      - notused:/opt/node_app/static_src/node_modules
    command: >
      sh -c "npm install &&
            npm run build-clean &&
            npm run build-postcss &&
            npm run dev"

  db:
    container_name: noones_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sora_password
      POSTGRES_USER: sora
      POSTGRES_DB: dev_db

volumes:
  notused:

secrets:
  email_user:
    file: ./email_user.txt
  email_pass:
    file: ./email_pass.txt
