# Generated by Django 3.0.3 on 2020-06-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20200529_2240'),
        ('clones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/updates')),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Photo')),
            ],
        ),
    ]
