# Generated by Django 3.0.2 on 2020-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200130_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
    ]
