# Generated by Django 3.0.2 on 2020-02-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200131_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Carousel',
        ),
    ]
