# Generated by Django 3.0.3 on 2020-02-13 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField()),
                ('model_nom', models.CharField(max_length=100)),
                ('model_email', models.EmailField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(choices=[('y', 'Oui'), ('n', 'Non')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=3)),
                ('taillenombrill', models.DecimalField(decimal_places=2, max_digits=3)),
                ('buste', models.IntegerField()),
                ('epaules', models.IntegerField()),
                ('hanches', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('pointure', models.IntegerField()),
                ('cheveux', models.CharField(max_length=100)),
                ('yeux', models.CharField(max_length=100)),
                ('permitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('sexe', models.CharField(choices=[('f', 'Femme'), ('h', 'Homme')], max_length=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('handle', models.SlugField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('phone', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=100)),
                ('profilePicture', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('coverPicture', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_public', models.BooleanField(default=False)),
                ('highlight', models.BooleanField(default=False)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.History')),
                ('measures', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Mensuration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('inUse', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
            ],
        ),
    ]
