# Generated by Django 3.0.7 on 2020-07-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='model_nom',
            new_name='model_full_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Model'),
        ),
    ]
