# Generated by Django 3.1.2 on 2021-02-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='q4',
            field=models.CharField(choices=[('y', 'Oui'), ('n', 'Non')], default=True, max_length=1),
        ),
    ]
