# Generated by Django 3.0.7 on 2020-06-06 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/updates')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
            ],
        ),
        migrations.CreateModel(
            name='MeasuresUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taillenombrill', models.DecimalField(
                    decimal_places=2, max_digits=5)),
                ('buste', models.IntegerField()),
                ('epaules', models.IntegerField()),
                ('hanches', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('pointure', models.IntegerField()),
                ('cheveux', models.CharField(max_length=100)),
                ('yeux', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('measure', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='models.Mensuration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
