# Generated by Django 3.0.7 on 2020-06-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200625_1539'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosupdate',
            name='related_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Photo'),
        ),
        migrations.CreateModel(
            name='CoverPictureUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accept', models.BooleanField(blank=True, null=True)),
                ('decline', models.BooleanField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=500)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
            ],
            options={
                'verbose_name_plural': 'Profile Cover Updates',
            },
        ),
    ]
