# Generated by Django 3.0.7 on 2020-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuresupdate',
            name='accept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measuresupdate',
            name='decline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measuresupdate',
            name='message',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
