# Generated by Django 3.0.7 on 2020-07-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accept', models.BooleanField(blank=True, null=True)),
                ('decline', models.BooleanField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=500)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Model')),
            ],
            options={
                'verbose_name_plural': 'Model Updates',
            },
        ),
    ]
