# Generated by Django 3.0.7 on 2020-06-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20200606_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosupdate',
            name='accept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photosupdate',
            name='decline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photosupdate',
            name='message',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
