# Generated by Django 3.1.2 on 2021-02-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20210206_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpictureupdate',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coverpictureupdate',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryupdate',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galleryupdate',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measuresupdate',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='measuresupdate',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepictureupdate',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilepictureupdate',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
    ]
