# Generated by Django 3.0.7 on 2020-06-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('updates', '0003_auto_20200610_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosupdate',
            name='related_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Photo'),
        ),
    ]
