# Generated by Django 3.0.7 on 2020-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_photosupdate_related_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosupdate',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
