# Generated by Django 3.0.7 on 2020-06-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('updates', '0005_auto_20200613_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosupdate',
            name='related_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.Photo'),
        ),
    ]
